#基本设置
name: 'Hugo Action'
description: 'FlySoloing Hugo Action'
author: 'flysoloing'
#
branding:
  icon: 'upload-cloud'
  color: 'blue'
#入参列表
inputs:
  theme_repo_url:
    description: 'hugo theme github repository, default is hugo-theme-qiuqiu'
    required: false
    default: 'https://github.com/flysoloing/hugo-theme-qiuqiu'
  source_repo_url:
    description: 'github article repository'
    required: true
  target_repo_url:
    description: 'github user or organization page, <USERNAME>.github.io'
    required: true
  config_file_url:
    description: 'hugo config file address'
    required: false
  base_url:
    description: 'site index page address'
    required: false
  site_title:
    description: 'site title'
    required: false
    default: 'FlySoloing'
  language_code:
    description: 'site language code'
    required: false
    default: 'en-us'
  theme_name:
    description: 'hugo theme name'
    required: false
    default: 'hugo-theme-qiuqiu'
#运行设置
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.theme_repo_url }}
    - ${{ inputs.source_repo_url }}
    - ${{ inputs.target_repo_url }}
    - ${{ inputs.config_file_url }}
    - ${{ inputs.base_url }}
    - ${{ inputs.site_title }}
    - ${{ inputs.language_code }}
    - ${{ inputs.theme_name }}
