# action.yml
name: 'Hugo Action'
description: 'Flysoloing Hugo Action'
author: 'flysoloing'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  theme_repo_url:
    description: 'hugo theme github repository, default is hugo-theme-even'
    required: false
    default: 'https://github.com/olOwOlo/hugo-theme-even'
  source_repo_url:
    description: 'github article repository'
    required: true
  target_repo_url:
    description: 'github user or organization page, <USERNAME>.github.io'
    required: true
  config_file_url:
    description: 'hugo config file address'
    required: false
  base_url:
    description: 'site index page address'
    required: false
  title:
    description: 'site title'
    required: false
    default: 'China No.1'
  language_code:
    description: 'site language code'
    required: false
    default: 'en-us'
  theme:
    description: 'hugo theme name'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.theme_repo_url }}
    - ${{ inputs.source_repo_url }}
    - ${{ inputs.target_repo_url }}
    - ${{ inputs.config_file_url }}
    - ${{ inputs.base_url }}
    - ${{ inputs.title }}
    - ${{ inputs.language_code }}
    - ${{ inputs.theme }}
